import type { Metadata } from "next";
import { Inter, Poppins, Plus_Jakarta_Sans } from "next/font/google";
import SWRProvider from "./components/swr-provider";
import { AuthProvider } from "@/lib/contexts/auth";

import "react-datepicker/dist/react-datepicker.css";
import "./globals.css";
import { OrgProvider } from "@/lib/contexts/org";
import { AlertContextProvider } from "@/lib/contexts/alert";
import Alert from "./components/alert";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const pJSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AlertContextProvider>
          <AuthProvider>
            <SWRProvider>
              <OrgProvider>
                {children}
                <Alert />
              </OrgProvider>
            </SWRProvider>
          </AuthProvider>
        </AlertContextProvider>
      </body>
    </html>
  );
}
